grafana_url: "https://support-training.hb.ru-msk.vkcloud-storage.ru/grafana-enterprise_12.2.0_17949786146_linux_amd64.tar.gz"
node_exporter_url: "https://support-training.hb.ru-msk.vkcloud-storage.ru/node_exporter-1.10.2.linux-amd64.tar.gz"
prometheus_url: "https://support-training.hb.ru-msk.vkcloud-storage.ru/prometheus-3.7.3.linux-amd64.tar.gz"
prometheus_version: "3.7.3"
node_exporter_version: "1.10.2"
grafana_versioh: "12.2.0"
grafana_domain: "grafana.supporttraining.ru"

node_exporter_listet_port: "9100"
skillbox_exporter_host: "lb.supporttraining.ru:8080"
skillbox_exporter_ip: "89.208.208.90"
skillbox_exporter_port: "8080"